# Cell container with jruby9+jre8
FROM atlo/cell-alpine
MAINTAINER Luis Diaz <ldiaz@atloideas.com>




ADD ruby_entry.sh /opt/ruby_entry.sh
RUN chmod u=rxw,g=rx,o=rx /opt/ruby_entry.sh

VOLUME ["/opt/ruby_run"]

ENTRYPOINT ["/opt/ruby_entry.sh"]
