[template]
src = "nginx.conf.tmpl"
dest = "/etc/nginx/nginx.conf"
uid = "nginx"
gid = "nginx"
mode = "0644"
keys = [
  "/nginx/conf",
  "/nginx/maintenance"
]
check_cmd = "/usr/sbin/nginx -t -c {{ .src }}"
reload_cmd = ""