[template]
src = "nginx.conf.tmpl"
dest = "/etc/nginx/nginx.conf"
uid = 0
gid = 0
mode = "0644"
keys = [
  "/nginx/conf",
  "/nginx/sites"
]
check_cmd = "/usr/sbin/nginx -t -c {{ .src }}"
reload_cmd = "echo reload"