[template]
src = "cassandra.yaml.tmpl"
dest = "/opt/cassandra/conf/cassandra.yaml"
uid = 1337
gid = 1337
mode = "0644"
keys = [
  "/cassandra/conf",
  "/cassandra/seeds",
]
# check_cmd = "" (no check)
reload_cmd = "touch /opt/cassandra_restart.txt && killall -q java ; echo 'killed!'"