# Cell container with RMV and ruby2
FROM atlo/ruby2
MAINTAINER Luis Diaz <ldiaz@atloideas.com>

RUN /bin/bash -l -c "gem install rails --version=4.2.1 --no-ri --no-rdoc && gem install thin --no-ri --no-rdoc"
